OBJS = helloWorld.cpp

#Shows what compiler were using
CC = g++

#compiler flag: -w supresses all warnings
COMPILER_FLAGS = -w

LINKER_FLAGS = -lSDL2

OBJ_NAME = helloWorld

all : $(OBJS)
				$(CC) $(OBJS) $(COMPILER_FLAGS) $(LINKER_FLAGS) -o $(OBJ_NAME)
